# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 3
updates:
  - package-ecosystem: "maven" # For java projects
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily" # Choose between "daily", "weekly", or "monthly"
      time: "2:35" # 2 AM UTC (which is 10:35 AM Philippine Time)
    commit-message:
      prefix: "fix: "
    allow:
      - dependency-type: "direct"  # Only update direct dependencies
