# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time

name: Build Active Directory Service

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Build the application using Maven
    - name: Build Project
      run: mvn -B clean package -DskipTests

    # Upload the built JAR file.
    - name: Upload JAR as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-jar-${{github.sha}} # Tagging maven build for better traceability.
        path: target/*.jar
      
    # TODO: The workflow permissions should be set to "Read and Write" to test this part.
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # Submitting the graph improves the quality of Dependabot’s checks.
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
